### PR TITLE
style: 💄 sourcery version update

### PR DESCRIPTION
**Pull request by xiaoyu0722**

### CODE REVIEW

**Comment by xiaoyu0722** [comment]
Do we also need `SwiftFormat` version update?

**Comment by billzhou0223** [comment]
> Hi @billzhou0223 Do we also need `SwiftFormat` version update? A lot `self.` added, which version used?

These changes were introduced by https://github.com/SAP/cloud-sdk-ios-fiori/pull/656/files. 

They shouldn't have been checked in. I've asked Janhua to revert them.

**Comment by janhuachu** [comment]
> > Hi @billzhou0223 Do we also need `SwiftFormat` version update? A lot `self.` added, which version used?
> 
> These changes were introduced by https://github.com/SAP/cloud-sdk-ios-fiori/pull/656/files.
> 
> They shouldn't have been checked in. I've asked Janhua to revert them.

@billzhou0223  I think my checked in removes the "self." which is expected right?

**Comment by billzhou0223** [comment]
We will take the changes from Janhus's PR. Close this PR since no changes needed now.

**Pull request closed without merging**
