### PR TITLE
feat: 🎸 add nav/popup mode for test app

### PR DESCRIPTION
**Pull request by shengxu7**

### CODE REVIEW

**Comment by MarcoEidinger** [comment]
@shengxu7 please add screenshot or gif to this PR to illustrate new nav/popup mode for test app

**Comment by shengxu7** [comment]
> @shengxu7 please add screenshot or gif to this PR to illustrate new nav/popup mode for test app

why?

**Comment by MarcoEidinger** [comment]
> > @shengxu7 please add screenshot or gif to this PR to illustrate new nav/popup mode for test app
> 
> why?

because it is good documentation and is just an effort of 5min or less. The PR is linked in Changelog and an interested party might wonder, click the link to details, and sees currently no textual or visual description. I believe we can do better

**Comment by shengxu7** [comment]
Preview mode:
Screen Shot 2020-10-21 at 3 22 05 PM

Mode Not Pop Up:
Screen Shot 2020-10-21 at 3 22 11 PM

Mode Pop Up:
Screen Shot 2020-10-21 at 3 22 23 PM

**Pull request merged**
