### PR TITLE
fix: 🐛 [JIRA:0] ThemeManager merge color definitions should not be called frequently

### PR DESCRIPTION
**Pull request by restaurantt**

### CODE REVIEW

**Review by billzhou0223 — CHANGES_REQUESTED** [review]
What's the point of this PR?

**Review by dyongxu — APPROVED** [review]
Note , after this is merged, need to update commit id on SAPFiori side (main branch).

Also,  this PR needs to be cherrypicked to FioriIntegration24.4 branch. Then update commit id for SAPFiori rel-24.4 branch.

**Comment by restaurantt** [comment]
> What's the point of this PR?

when tableView is scrolling, func `mergedDeprecatedDefinitions` be called too many times

**Review by dyongxu — APPROVED** [review]

**Comment by restaurantt** [comment]
When I fixed internal project JIRA: IOSSDKBUG-220 Cards TableView scrolling is not smooth.
I use "Instruments" to watch why Cards TableView scrolling is not smooth. The result shows func mergedDeprecatedDefinitions in ThemeManager costs most time, especially the official merge func in mergedDeprecatedDefinitions . Look into the code, it merges the color by sdk version. and never changed because sdk version is fixed. So I use a variable to store the merged result.
I found this issue exists in this project, so create this pr.
instrument screenshot

**Comment by dyongxu** [comment]
@billzhou0223  Do you have some requested change to be addressed by Jianjun ?  I am not able to find the request.

**Comment by billzhou0223** [comment]
> @billzhou0223 Do you have some requested change to be addressed by Jianjun ? I am not able to find the request.

My comments were for this commit [435caad](https://github.com/SAP/cloud-sdk-ios-fiori/pull/718/commits/435caad97852d298ddaf470fdc6008fc73422560). He updated the implementation in the latest commit and it looks ok now.

**Review by billzhou0223 — APPROVED** [review]

**Pull request merged**
