### PR TITLE
chore: 🤖 new private/internal model variables for emptView det

### PR DESCRIPTION
**Pull request by MarcoEidinger**
being able to identify if `EmptyView` is used for a view (e.g. Subtitle)

### CODE REVIEW

**Comment by MarcoEidinger** [comment]
Hi @shengxu7 , this PR should be able to generate the code you expect in order to determine if `EmptyView` is being used for a particular `View`. Can you please verify?

**Review by shengxu7 — COMMENTED** [review]
ObjectItem+API.generated.swift: need to add "private var isIconsNil: Bool = false" and "var isIconsEmptyView: Bool"

**Comment by MarcoEidinger** [comment]
> ObjectItem+API.generated.swift: need to add "private var isIconsNil: Bool = false" and "var isIconsEmptyView: Bool"

@shengxu7 will this not be generated for your source code?

You will not find this in my checked-in code as`ObjectItem` does not have a `icons` component on the migration branch

`// sourcery: generated_component
public protocol ObjectItemModel: TitleComponent, SubtitleComponent, FootnoteComponent, DescriptionTextComponent, StatusComponent, SubstatusComponent, DetailImageComponent {}`)

**Review by shengxu7 — APPROVED** [review]

**Comment by MarcoEidinger** [comment]
@billzhou0223 are you fine with the generated changes?

**Review by billzhou0223 — APPROVED** [review]

**Pull request merged**
