### PR TITLE
fix: 🐛 Serbian and Croatian translations

### PR DESCRIPTION
**Pull request by Kukurijek**
Resolves: #304

### CODE REVIEW

**Comment by MarcoEidinger** [comment]
Thanks for opening up the PR! Our translation coordinator is currently checking this so please give us until tomorrow

**Comment by Kukurijek** [comment]
`PR / SnapshotTests (pull_request)` job failed. Is this really related to my change ? 😅 
I have not found any test that uses these translations.

**Comment by MarcoEidinger** [comment]
@Kukurijek don't worry, this is unrelated to your change :) I also wanted to share an update from our translation coordinator. Apparently, there are translation style guides for languages from SAP so your proposal is currently reviewed to avoid any inconsistencies. This might take a bit. Nothing to do from your side. Enjoy the weekend and thanks again for your input!

**Comment by MarcoEidinger** [comment]
Hi @Kukurijek,

I want to let you know that I very much appreciate your input! You took time off your busy day to provide feedback which is something special. You challenged the translation team to review the current translation. This is a good thing and on behalf of the team I say "Thank you" !!

Good news: the review triggered an improvement (#310) to the Croatian translation of “Tap to Sign”.
Bad news: unfortunately the given feedback cannot be accepted as a whole as the verbs in question should be left in the imperative form according to the SAP translation style guides.

Therefore I will close this pull request and related issue #304.

**Comment by Kukurijek** [comment]
Hi @MarcoEidinger,

Thank you for taking time for reviewing and improving the translation.
I am glad I was helpful :)

**Pull request closed without merging**
