### PR TITLE
fix: 🐛 add a discloure icon for navigation test

### PR DESCRIPTION
**Pull request by xiaoyu0722**
|before|after|
|-|-|
|Simulator Screenshot - iPhone 15 Pro Max - 2024-06-26 at 15 41 57|Simulator Screenshot - iPhone 15 Pro Max - 2024-06-26 at 16 01 46|

### CODE REVIEW

**Review by billzhou0223 — CHANGES_REQUESTED** [review]
Your setup looks uncommon.. Would this be better?

```
NavigationLink {
                    EmptyView()
                } label: {
                    Text("FioriStyle Version")
                }
```

**Comment by xiaoyu0722** [comment]
> Your setup looks uncommon.. Would this be better?
> 
> ```
> NavigationLink {
>                     EmptyView()
>                 } label: {
>                     Text("FioriStyle Version")
>                 }
> ```

No, if use `NavigationLink` directly, an empty view will be pushed when you tap on the cell a bit longer, like 1 second.
Tap gesture will be ignored, which should toggle `isPresented`.
I just need a system disclosure icon, not the navigation link.

**Comment by billzhou0223** [comment]
> > Your setup looks uncommon.. Would this be better?
> > ```
> > NavigationLink {
> >                     EmptyView()
> >                 } label: {
> >                     Text("FioriStyle Version")
> >                 }
> > ```
> 
> No, if use `NavigationLink` directly, an empty view will be pushed when you tap on the cell a bit longer, like 1 second. Tap gesture will be ignored, which should toggle `isPresented`. I just need a system disclosure icon, not the navigation link.

If you don't need the navigation action, don't use NavigationLink. I assume it will still trigger navigation if you tap on the disclosure. Just adding a sf symbol should be enough.

**Comment by xiaoyu0722** [comment]
SF symbol is not exactly same as disclosure icon in navigation link.
Anyway, it seems to be a design defect, disclosure icon should not be used in sheet presentation.

**Comment by billzhou0223** [comment]
> SF symbol is not exactly same as disclosure icon in navigation link. Anyway, it seems to be a design defect, disclosure icon should not be used in sheet presentation.

If it's a wrong design, can we close this PR? The change is in test app and won't affect SDK component anyway.

**Comment by xiaoyu0722** [comment]
Hi @billzhou0223 
I use sf symbol for it, and the style is basically same with the system's. 🤣

**Review by dyongxu — APPROVED** [review]

**Comment by dyongxu** [comment]
@billzhou0223 Is this PR ready for merge ? Or change requested ?

**Review by billzhou0223 — APPROVED** [review]

**Pull request merged**
