### PR TITLE
refactor: central demo application

### PR DESCRIPTION
**Pull request by MarcoEidinger**
unify the different dev and demo apps into a single app to illustrate examples of the provided UI
components

### CODE REVIEW

**Comment by MarcoEidinger** [comment]
I'd like to unify the various apps into a single demo app.

Motivation
- better marketing
- can be used as a foundation to run snapshot tests

Any reasons not to do so?

@shengxu7 please check the app related to charts
@ShawnMa16 please check the app related for integration cards

I have not yet beautified the app. It is basically a direct blend of the three previous apps.

The three previous apps still have to be deleted. I just deleted the references in the workspace. **Please leave your review** and I'll amend the commit with related change before merging.

**Comment by MarcoEidinger** [comment]
@shengxu7 and @ShawnMa16 : please provide feedback until tomorrow (Tuesday) lunch time. Thanks in advance :)

**Comment by sstadelman** [comment]
@MarcoEidinger I think that's fine.  The trick will be keeping the feature discovery manageable--see the ReusableUITestApplication as evidence.  Maybe we can use the new SwiftUI hierarchical lists?

**Comment by MarcoEidinger** [comment]
I amended my PR to fix the issue that icons are not loaded for cards. Thanks @ShawnMa16 for the feedback.

@shengxu7 any feedback or concerns?

Before I merge (around 1pm unless I hear a veto) I'll do another amend to delete the three previous apps. 

@sstadelman I'll create an issue and add it to the backlog to use new SwiftUI hierarchical list.

**Comment by MarcoEidinger** [comment]
Thanks to everyone for the feedback and review. Here is the final result

ExamplesApp

**Pull request merged**
