### PR TITLE
Translation Delivery

### PR DESCRIPTION
**Pull request by service-tip-git**
Translation Delivery

### CODE REVIEW

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by dyongxu** [comment]
Translation team to rename cnr.lproj. Do not merge yet.

**Comment by service-tip-git** [comment]
This pull request is for translation delivery. Please review and approve them.

**Comment by dyongxu** [comment]
@service-tip-git Still see the cnr.lproj file in the package. To be confirmed by translation team if to be renamed.

**Comment by dyongxu** [comment]
Closed this one. Translation team will do another PR to rename "cnr.lproj".

**Pull request closed without merging**
