### PR TITLE
chore: use SwiftFormat (in addition to SwiftLint)

### PR DESCRIPTION
**Pull request by MarcoEidinger**
# What is this?

SwiftFormat (https://github.com/nicklockwood/SwiftFormat) is a code library and command-line tool for reformatting Swift code on macOS or Linux.

SwiftFormat goes above and beyond what you might expect from a code formatter. In addition to adjusting white space it can insert or remove implicit self, remove redundant parentheses, and correct many other deviations from the standard Swift idioms.

# Why would we want to do that?
Many programmers have a preferred style for formatting their code, and others seem entirely blind to the existing formatting conventions of a project (to the enragement of their colleagues).

When collaborating on a project, it can be helpful to agree on a common coding style, but enforcing that manually is tedious and error-prone, and can lead to arguments if some participants take it more seriously than others.

Having a tool to automatically enforce a common style eliminates those issues, and lets you focus on the behavior of the code, not its presentation.

# How to setup for developer locally

Integrated in existing `setupForCollaborators` shell script

setupForCollaborators

Using `mint` (vs `brew`) allows to pin to a specific version of `swiftformat` (and `swiftlint`) which is a significant advantage. But mint checks out and build swift packages and this is slower which results in making the shell script slower (= disadvantage). Hence I added info to output when you can start working while the script may still run :)

# How to use it in daily work

Runs automatically on `git commit` for staged files

# Existing code base?

Adjusted with the second commit **with exception** *no FioriCharts related sources changed. Will be done with subsequent PR from @shengxu7*

# Expected Discussion Points (Controversial)

1. Developers might feel bad by the current rule to strip the file header and hence author information gets deleted. This can be changed (to ignore and keep header) but here is my argument why stripping the header is justified.

whyStripHeader

2. The keyword `self` is in rare cases required but in most it is redundant. There is no tool which can identify when it is needed. The current proposal is to always `insert`. This is in contradiction to SwiftFormat default shipment. See [redundantSelf rule](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#redundantSelf) for details

3. Other individual rules? See [.swiftformat](https://github.com/SAP/cloud-sdk-ios-fiori/compare/main...MarcoEidinger:swiftformat?expand=1#diff-716e9196614e4df70d21cfe5515e79b2695a42931ca929e2654c88e27c081245) for current proposal of rules

# Next steps

~~My proposal is to present this in our next Demo meeting, then @shengxu7 and @billzhou0223 try it out (you can easily checkout this PR with [GitHub CLI](https://cli.github.com/)) and provide feedback~~

Positive feedback from @shengxu7 and @billzhou0223

### CODE REVIEW

**Comment by shengxu7** [comment]
Next week we are going to release FioriCharts. I think it is not good idea to run SwiftFormat for existing code base right now. Can you remove the commit "chore: run SwiftFormat for existing code base" for this PR?

**Comment by MarcoEidinger** [comment]
> Next week we are going to release FioriCharts. I think it is not good idea to run SwiftFormat for existing code base right now. Can you remove the commit "chore: run SwiftFormat for existing code base" for this PR?

thanks @shengxu7 for voicing your concerns. We can hold off to merge the PR for sure but we should aim for a target date to merge. What about Nov 10th? Would this fit?

@billzhou0223  and @shengxu7 any feedback on the concrete rules/formatting which will be enforced?

P.S.: I don't want to merge the tooling without adapting the existing code base. The reasoning is that, once tooling is merged, any further changes will be formatted. Not only the exact lines of code in future PRs but the whole file(s). And if we are truly concerned about last-minute changes then we shouldn't do this.

**Comment by MarcoEidinger** [comment]
I'd like to get your input here @billzhou0223 , thanks in advance

**Comment by billzhou0223** [comment]
> I'd like to get your input here @billzhou0223 , thanks in advance

Sorry I didn't notice this earlier.

I like the idea of using tooling to enforce standard code style. In order to avoid significant amount of code changes prior to release date, it's better to hold off on this until release is in place.

**Comment by MarcoEidinger** [comment]
Request from @shengxu7 to exclude code adjustments for FioriCharts

> I am working on a new feature about zoom which will touch most of files in firoricharts. it  will be very difficult for me to merge the pr. so I think it is better for me to run swiftformt for fioricharts later.

I don't want to put extra efforts into adjusting checks excluding certain directories but I can take out FioriCharts related sources from commit "chore: run SwiftFormat for existing code base". The consequence would be that PR status check will fail for subsequent PRs (due to incorrectly formatted files in repo) until @shengxu7 checks-in his latest development properly formatting with swiftformat.

@shengxu7 I assume the new feature will be ready within 2 weeks?

I can live with that for that long. @billzhou0223 ?

**Comment by MarcoEidinger** [comment]
> Request from @shengxu7 to exclude code adjustments for FioriCharts
> 
> > I am working on a new feature about zoom which will touch most of files in firoricharts. it  will be very difficult for me to merge the pr. so I think it is better for me to run swiftformt for fioricharts later.
> 
> I don't want to put extra efforts into adjusting checks excluding certain directories but I can take out FioriCharts related sources from commit "chore: run SwiftFormat for existing code base". The consequence would be that PR status check will fail for subsequent PRs (due to incorrectly formatted files in repo) until @shengxu7 checks-in his latest development properly formatting with swiftformat.
> 
> @shengxu7 I assume the new feature will be ready within 2 weeks?
> 
> I can live with that for that long. @billzhou0223 ?

I ran SwiftFormat for existing code base exl. FioriCharts

@shengxu7 and @billzhou0223 : please review and comment

**Review by billzhou0223 — APPROVED** [review]

**Comment by MarcoEidinger** [comment]
According to @shengxu7 it might take longer than 2 weeks to push his latest development incl. proper code formatting. Neverthless, let's merge this PR. For subsequent PR
s the mandatory build checks will pass but the check for code formatting will fail (non-blocking for merge) as the repo has unformatted changes.

**Pull request merged**
